nginx:
    build: ./docker/nginx/
    ports:
        - "8080:80"
        - "8443:443"
    volumes:
        - /etc/nginx/psw:/etc/nginx/pws
        - /etc/nginx/ssl:/etc/nginx/ssl
        - ./nginx/nginx.conf:/etc/nginx/conf.d/dock.loc
    environment:
        - DOMAIN_NAME=smarthome.loc
    links:
        - node
node:
    build: .
    ports:
        - "8888:88"
        - "3800:3000"
    volumes:
        - ./:/home/app/homebackend
    environment:
        MONGO_HOST: models
        MONGO_PORT: 37017
    links:
        - mongodb
mongodb:
     build: ./docker/mongodb/
     #command: [" --smallfiles --quiet --logpath=/dev/null","chmod -R 0755 mongodb/journal"]
     ports:
         - "37017:27017"
     #command: chmod -R 0777 /data/db
     volumes:
         - ./mongodb:/data/db
