#nginx:
#    build: ./nginx/
#    ports:
#        - "8080:80"
#        - "8443:443"
#    volumes:
#        - /etc/nginx/psw:/etc/nginx/pws
#        - /etc/nginx/ssl:/etc/nginx/ssl
#        - ./nginx/nginx.conf:/etc/nginx/conf.d/dock.loc
#    environment:
#        - DOMAIN_NAME=dock.loc
#    links:
#        - node
node:
    image: kubrey/node-test-app
    ports:
        - "8800:80"
    command: echo 'ready'
    volumes:
        - ./:/home/app/homebackend
        - /home/app/homebackend/node_modules
    environment:
        MONGO_HOST: mongo
        MONGO_PORT: 27017
    links:
        - mongodb

mongodb:
     image: mongo:3.0
     command: mongod --smallfiles --quiet --logpath=/dev/null
     ports:
         - 37017:27017
  #   command: chmod -R 0755 mongodb/journal
     volumes:
         - ./mongodb:/data/db
