#nginx:
#    build: ./nginx/
#    ports:
#        - "8080:80"
#        - "8443:443"
#    volumes:
#        - /etc/nginx/psw:/etc/nginx/pws
#        - /etc/nginx/ssl:/etc/nginx/ssl
#        - ./nginx/nginx.conf:/etc/nginx/conf.d/dock.loc
#    environment:
#        - DOMAIN_NAME=dock.loc
#    links:
#        - node

node:
#    image: kubrey/node-test-app
    build: .
    ports:
        - "8800:80"
        - "3000:3000"
    volumes:
        - ./:/home/app/homebackend
#        - ./node_modules:/home/app/homebackend/node_modules
    environment:
        MONGO_HOST: mongo
        MONGO_PORT: 37017
    links:
        - mongodb

mongodb:
     image: mongo:3.0
     command: " --smallfiles --quiet --logpath=/dev/null"
     ports:
         - "37017:27017"
  #   command: chmod -R 0755 mongodb/journal
#     volumes:
#         - ./mongodb:/data/db
