nginx:
    build: ./nginx
    ports:
        - "8080:80"
        - "8443:443"
    volumes:
        - /etc/nginx/psw:/etc/nginx/pws
        - /etc/nginx/ssl:/etc/nginx/ssl
    environment:
        - DOMAIN_NAME=homenode.loc
    links:
        - node
node:
    build: ./node
    ports:
        - "8800"
    volumes:
        - ../:/var/www/homenode/data/www/homenode.loc
    environment:
        MONGO_HOST: mongo
        MONGO_PORT: 27017
    links:
        - mongodb

mongodb:
     image: mongo:3.0
     command: mongod --smallfiles --quiet --logpath=/dev/null
     ports:
         - 37017:27017
     volumes:
         - ./mongodb:/data/db
