nginx:
    build: ./nginx/
    ports:
        - "8080:80"
        - "8443:443"
    volumes:
        - /etc/nginx/psw:/etc/nginx/pws
        - /etc/nginx/ssl:/etc/nginx/ssl
        - ./nginx/nginx.conf:/etc/nginx/conf.d/dock.loc
    environment:
        - DOMAIN_NAME=dock.loc
    links:
        - node
node:
    build: ./node/
    ports:
        - "8800:80"
    volumes:
        - ../:/app
    environment:
        MONGO_HOST: models
        MONGO_PORT: 27017
    links:
        - mongodb

mongodb:
     image: models:3.0
     command: mongod --smallfiles --quiet --logpath=/dev/null
     ports:
         - 37017:27017
     volumes:
         - ./mongodb:/data/db
